apiVersion: v1
kind: Service
metadata:
  name: studyquest-backend-service
spec:
  type: ClusterIP
  selector:
    app: studyquest-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000